### PR TITLE
Improve performance on large folders by 10x or more

### PR DESCRIPTION
**Pull request by samsonjs**
I was kind of frustrated with how long it took to run on large folders when the mail was mostly already downloaded, and I didn't always want to exclude them from my regular backups so I started reading up on IMAP a little bit and found a way to get a really good performance boost.

IMAP allows fetching message IDs for all messages in a folder at once and it's quite a bit faster than making individual requests. Running this on a folder with 4441 messages takes 26s for me now compared to over 8 minutes before this change.

Here's the current master branch processing one folder with 599 messages in just over a minute:
```
[ 4:25pm] ~/Backup/fastmail-email % time imapbackup38.py --ssl --server=imap.fastmail.com --user=someone@example.net --pass=secret --mbox-dir=. --folders=Years/2009
Connecting to 'imap.fastmail.com' TCP port 993, SSL
Logging in as 'someone@example.net'
Finding Folders /(\HasNoChildren) "/" INBOX
(\HasNoChildren \Archive) "/" Archive
...
(\HasChildren) "/" Years
(\HasNoChildren) "/" Years/2004
...
(\HasNoChildren) "/" Years/2021
Finding Folders: 37 folders
File Years.2009.mbox: 600 messages
Folder "Years/2009":
599 messages
New messages: 0
Disconnecting
imapbackup38.py --ssl  --user=someone@example.net  0.89s user 0.17s system 1% cpu 1:04.78 total
```

And this branch on the same folder in 2 seconds:

```
[ 4:27pm] ~/Backup/fastmail-email % time imapbackup38-fast.py --ssl --server=imap.fastmail.com --user=someone@example.net --pass=secret --mbox-dir=. --folders=Years/2009
Connecting to 'imap.fastmail.com' TCP port 993, SSL
Logging in as 'someone@example.net'
Finding Folders /(\HasNoChildren) "/" INBOX
(\HasNoChildren \Archive) "/" Archive
...
(\HasChildren) "/" Years
(\HasNoChildren) "/" Years/2004
...
(\HasNoChildren) "/" Years/2021
Finding Folders: 37 folders
File Years.2009.mbox: 600 messages
Folder "Years/2009":
599 messages
New messages: 0
Disconnecting
imapbackup38-fast.py --ssl --server=imap.fastmail.com      0.75s user 0.10s system 39% cpu 2.137 total
```

Now the current master branch on a folder with 4441 messages:

```
[ 4:27pm] ~/Backup/fastmail-email % time imapbackup38.py --ssl --server=imap.fastmail.com --user=someone@example.net --pass=secret --mbox-dir=. --folders=Years/2021
Connecting to 'imap.fastmail.com' TCP port 993, SSL
Logging in as 'someone@example.net'
Finding Folders /(\HasNoChildren) "/" INBOX
(\HasNoChildren \Archive) "/" Archive
...
(\HasChildren) "/" Years
(\HasNoChildren) "/" Years/2004
...
(\HasNoChildren) "/" Years/2021
Finding Folders: 37 folders
File Years.2021.mbox: 4441 messages
Folder "Years/2021":
4441 messages
New messages: 0
Disconnecting
imapbackup38.py --ssl  --user=someone@example.net  22.47s user 3.51s system 5% cpu 8:13.32 total
```

And this branch on the same folder in 26 seconds:

```
[ 4:36pm] ~/Backup/fastmail-email % time imapbackup38-fast.py --ssl --server=imap.fastmail.com --user=someone@example.net --pass=secret --mbox-dir=. --folders=Years/2021
Connecting to 'imap.fastmail.com' TCP port 993, SSL
Logging in as 'someone@example.net'
Finding Folders /(\HasNoChildren) "/" INBOX
(\HasNoChildren \Archive) "/" Archive
...
(\HasChildren) "/" Years
(\HasNoChildren) "/" Years/2004
...
(\HasNoChildren) "/" Years/2021
Finding Folders: 37 folders
File Years.2021.mbox: 4441 messages
4441 messages
New messages: 0
Disconnecting
imapbackup38-fast.py --ssl --server=imap.fastmail.com      21.53s user 2.91s system 93% cpu 26.233 total
```

### CODE REVIEW

**Comment by rcarmo** [comment]
I’m fine with this, would just like to have someone else test it against more IMAP servers (which is a pain).

**Comment by samsonjs** [comment]
Yeah that's a good idea. I'm not familiar with IMAP at all and I just found this in a tutorial so I have no idea how portable it is. According to the spec the fetch command accepts a "sequence set" and they use a range in their example, but I can't find a definition of that term anywhere. https://datatracker.ietf.org/doc/html/rfc3501#section-6.4.5

I'm going to do a bit more testing as well by downloading some folders with the current master branch and then this branch and diffing the resulting mbox files. Then updating each set of files and diff again, things like that. I started down that road and found some old, broken emails but I tracked them down and deleted them and can proceed with that testing at some point. But because we're indexing into the resulting data array using num_msgs I'm pretty confident that if something was missing it would blow up. But you never know until you test it.

**Comment by samsonjs** [comment]
Trying to compare some of my folders is difficult because email is always changing so my inbox, sent, and some other folders don't match. I also had to unify all of the "From " lines because they have generated timestamps in them by default, and sed is unhappy that the files aren't UTF-8. Anyway after crafting up this command to munge all of the From lines, so far it looks like this branch creates identical output to master which is great!

```zsh
for f in *.mbox; do
    echo ">>> $f <<<"
    iconv -f ISO-8859-1 -t UTF8-MAC "$f" | sed -e 's/^From nobody .*$/From nobody Mon Jan  3 11:55:08 2022/' > "$f.new"
done
```

Screen Shot 2022-01-03 at 3 25 55 PM

```zsh
% diff -qruN master-munged fast-munged
Files master-munged/INBOX.mbox and fast-munged/INBOX.mbox differ
Files master-munged/Sent.mbox and fast-munged/Sent.mbox differ
Files master-munged/Spam.mbox and fast-munged/Spam.mbox differ
Files master-munged/Trash.mbox and fast-munged/Trash.mbox differ
Files master-munged/checksums.txt and fast-munged/checksums.txt differ
```

**Comment by rcarmo** [comment]
Oh, yes, these things are quite hard to test on live mailboxes, for a number of reasons... There were two that gave me some headaches in the past:
* Different IMAP servers have different policies for IMAP message IDs (i.e., message 10 may only be message 10 during a single session, or be directly coupled to the message itself, etc.)
* Deleted messages (flagged for deletion but not expunged or moved to another folder) sometimes lounge about for no apparent reason
Gmail was notorious for handling deletes/moves poorly, for instance.

**Comment by samsonjs** [comment]
Good times! 😆

**Comment by rcarmo** [comment]
Merging this since I think the approach should work with all IMAP servers during the same backup run.

**Pull request merged**
